#!/usr/bin/env python3
"""
Self-contained authenticated command channel over 127.0.0.1:9999.

One file, both ends, no socat / no helper processes:

    server (as root):   sudo ./sudo_listener.py [--port N]     # "serve" is the default
    client (as you):         ./sudo_listener.py run [--port N] '<shell command>'

The server binds the port, serves each connection in a thread, authenticates the
request with HMAC-SHA256 over a pre-shared key, runs the command as its own uid
(root when the server is root), and streams the reply back. The client signs the
request, sends it, and demuxes the reply to its own stdout/stderr/exit code.

Auth / integrity / anti-replay:
  - PSK: a 0600 file (auto-generated by `serve` on first run); the key itself is
    never transmitted, only an HMAC over the request. Launch the server via sudo
    so the key is created in the invoking user's home and chowned to them, so the
    unprivileged client can read it too. On load the PSK is opened O_NOFOLLOW and
    its fd is fstat-checked: it must be a regular file, mode 0600, owned by root
    or the invoking/current user, else it is refused (a pre-planted key is never
    adopted).
  - Anti-replay: each request carries a wall-clock nanosecond timestamp and must
    be strictly greater than the highest one accepted so far - an in-memory
    high-water mark seeded at the server's startup time (not persisted; on restart
    it resets to the new startup, still rejecting older). Client and server share
    one wall clock (same host), so nothing is exchanged; a small future tolerance
    bounds clock jitter. NB this is a wall-clock high-water mark, not a monotonic
    clock: a backward wall-clock step (NTP/manual) can transiently reject requests
    until the clock catches up. The nonce is HMAC salt only - replay is handled by
    the timestamp floor, not by tracking nonces.
  - The command is base64-encoded (validate=True) on the wire, so exact bytes are
    authenticated and no shell quoting survives transport.

Request line (single line):  <ts_ns> <nonce_hex> <hmac_hex> <b64cmd>\\n
    hmac = HMAC-SHA256(psk, b"<ts_ns>.<nonce_hex>.<b64cmd>")
Reply: length-framed, stream-tagged chunks:
    frame = tag(1) | length(4, big-endian uint) | payload
        tag 1 = stdout, tag 2 = stderr, tag 3 = exit (4-byte signed rc),
        tag 4 = rejected (payload = ASCII reason; client retries when "stale*")

Config via env (defaults shown): ROOTRUN_PSK=<invoking user's ~>/.rootrun_psk,
ROOTRUN_HOST=127.0.0.1, ROOTRUN_PORT=9999, ROOTRUN_QUIET=(unset).

SECURITY: this runs ARBITRARY COMMANDS AS ROOT for anyone who can produce a valid
HMAC, i.e. anyone who can read the PSK file. It is exactly as strong as that file's
permissions (0600) and the loopback bind. Treat the PSK as a root credential, and
keep it in a directory only you (or root) can write.
"""
import os, sys, socket, struct, hmac, hashlib, base64, time, select, subprocess, signal, threading, stat, pwd

FUTURE_TOLERANCE_NS = 1 * 10**9  # accept timestamps at most this far ahead of now [ns]; same host, so small
REQUEST_TIMEOUT = 10  # a client must send its request line within this many seconds
MAX_CONNECTIONS = 64  # cap concurrent connection threads (slow-loris / fd-exhaustion guard)
MAX_FRAME = 256 * 1024 * 1024  # client: reject a single reply frame larger than this
RETRIES = 5  # client: attempts when the server rejects a request as stale (lost a race)


def _default_psk_path():
    # One path for the root server (launched via sudo) and the unprivileged client:
    # prefer $ROOTRUN_PSK; else the invoking user's home ($SUDO_USER under sudo);
    # else the current user's home. ensure_psk() chowns it to that user.
    env = os.environ.get("ROOTRUN_PSK")
    if env:
        return env
    user = os.environ.get("SUDO_USER")
    if user:
        try:
            return os.path.join(pwd.getpwnam(user).pw_dir, ".rootrun_psk")
        except KeyError:
            pass
    return os.path.expanduser("~/.rootrun_psk")


PSK_PATH = _default_psk_path()
HOST = os.environ.get("ROOTRUN_HOST", "127.0.0.1")
PORT = int(os.environ.get("ROOTRUN_PORT", "9999"))
QUIET = bool(os.environ.get("ROOTRUN_QUIET"))  # if set, do NOT echo command output to the server log

_io_lock = threading.Lock()  # serialise writes to the server's stderr (log lines + output tee)
_conn_sem = threading.BoundedSemaphore(MAX_CONNECTIONS)


def log(msg):
    # One timestamped server-side audit line, written under the io lock so concurrent
    # connection threads (and the output tee) never interleave mid-line.
    with _io_lock:
        sys.stderr.write("%s %s\n" % (time.strftime("%Y-%m-%d %H:%M:%S"), msg))
        sys.stderr.flush()


def _trusted_uids():
    # uids whose ownership of the PSK we trust: root, the current process, and (server
    # side) the sudo invoker the key is meant for.
    uids = {0, os.getuid()}
    su = os.environ.get("SUDO_USER")
    if su:
        try:
            uids.add(pwd.getpwnam(su).pw_uid)
        except KeyError:
            pass
    return uids


def load_psk():
    # TOCTOU-safe: open without following symlinks, validate the fd's stat, then read.
    # Refuses anything an attacker could have planted (wrong owner/mode/type).
    fd = os.open(PSK_PATH, os.O_RDONLY | os.O_NOFOLLOW)
    try:
        st = os.fstat(fd)
        if not stat.S_ISREG(st.st_mode):
            raise PermissionError("PSK %s is not a regular file" % PSK_PATH)
        if st.st_mode & 0o077:
            raise PermissionError("PSK %s permissions %04o too open (want 0600)" % (PSK_PATH, stat.S_IMODE(st.st_mode)))
        if st.st_uid not in _trusted_uids():
            raise PermissionError("PSK %s owned by untrusted uid %d" % (PSK_PATH, st.st_uid))
        data = os.read(fd, 4096)
    finally:
        os.close(fd)
    return data.strip()


def ensure_psk():
    # Server-side: create the PSK if absent, else validate the existing one (never
    # adopt a pre-planted key). O_EXCL makes creation atomic and refuses symlinks.
    if os.path.exists(PSK_PATH):
        try:
            load_psk()
        except OSError as e:
            sys.exit("sudo_listener: refusing to use existing PSK: %s" % e)
        return
    key = base64.b64encode(os.urandom(32))
    fd = os.open(PSK_PATH, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    try:
        os.write(fd, key + b"\n")
    finally:
        os.close(fd)
    # Hand the key to the intended unprivileged client (the sudo invoker), not to
    # whoever happens to own the directory.
    su = os.environ.get("SUDO_USER")
    if os.geteuid() == 0 and su:
        try:
            pw = pwd.getpwnam(su)
            os.chown(PSK_PATH, pw.pw_uid, pw.pw_gid)
        except (KeyError, OSError):
            pass
    log("generated new PSK at %s" % PSK_PATH)


def send_frame(sock, tag, payload):
    sock.sendall(bytes([tag]) + struct.pack(">I", len(payload)) + payload)


def read_request_line(sock):
    # The request is one newline-terminated line; read only up to the newline so we
    # never depend on the client closing its write side (no half-close timeout games).
    # If the line passes the cap before a newline arrives, say so (request-too-long)
    # rather than silently truncating and later failing the HMAC as a misleading
    # "auth-failed".
    limit = 1 << 16  # 64 KiB
    buf = b""
    while b"\n" not in buf:
        if len(buf) >= limit:
            raise ValueError("request-too-long")
        c = sock.recv(4096)
        if not c:
            break
        buf += c
    return buf.split(b"\n", 1)[0]


def _child_env():
    # A fixed, minimal environment for the root command, so a bare binary name can't
    # resolve via a user-influenceable PATH regardless of how the server was launched.
    try:
        home = pwd.getpwuid(os.geteuid()).pw_dir
    except KeyError:
        home = "/root"
    return {
        "PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
        "HOME": home,
        "LANG": os.environ.get("LANG", "C.UTF-8"),
    }


# ---------------------------------------------------------------- server side
class ReplayGuard:
    """Anti-replay high-water mark: a single in-memory wall-clock ns timestamp,
    seeded to the server's startup time and advanced under a lock. Every accepted
    request must carry a strictly larger timestamp than any prior one. Not persisted:
    on restart it resets to the new startup, still rejecting anything older."""

    def __init__(self):
        self._floor = time.time_ns()
        self._lock = threading.Lock()

    def check(self, ts_ns):
        # Returns None to accept (and advances the floor), else a rejection reason.
        now = time.time_ns()
        with self._lock:
            if ts_ns > now + FUTURE_TOLERANCE_NS:
                return "future-timestamp"
            if ts_ns <= self._floor:
                return "stale-or-replay"
            self._floor = ts_ns
            return None


def reject(conn, peer, reason):
    # Tag-4 frame so the client can tell a rejection from command output, and retry
    # a stale-race rejection instead of treating it as a failed command.
    log("%s rejected: %s" % (peer, reason))
    try:
        send_frame(conn, 4, reason.encode())
    except OSError:
        pass


def handle(conn, addr, guard):
    peer = "%s:%d" % addr
    try:
        psk = load_psk()
        conn.settimeout(REQUEST_TIMEOUT)
        try:
            line = read_request_line(conn).rstrip(b"\r")
        except socket.timeout:
            reject(conn, peer, "no-request-within-timeout")
            return
        except ValueError:
            reject(conn, peer, "request-too-long")
            return
        conn.settimeout(None)  # the command itself may run arbitrarily long

        parts = line.split(b" ", 3)
        if len(parts) != 4:
            reject(conn, peer, "malformed-request")
            return
        ts_b, nonce, mac_hex, b64 = parts

        expected = hmac.new(psk, b"%s.%s.%s" % (ts_b, nonce, b64), hashlib.sha256).hexdigest().encode()
        if not hmac.compare_digest(expected, mac_hex):
            reject(conn, peer, "auth-failed")
            return

        try:
            ts = int(ts_b)
        except ValueError:
            reject(conn, peer, "bad-timestamp")
            return
        verdict = guard.check(ts)
        if verdict:
            reject(conn, peer, verdict)
            return

        try:
            cmd = base64.b64decode(b64, validate=True).decode("utf-8", "surrogateescape")
        except Exception:
            reject(conn, peer, "bad-command-encoding")
            return

        shown = cmd if len(cmd) <= 800 else cmd[:800] + (" ...[+%d chars]" % (len(cmd) - 800))
        log("%s RUN: %s" % (peer, shown))
        t0 = time.time()
        # Run each command in its own session with no controlling terminal
        # (start_new_session => setsid). stdin=DEVNULL detaches the child from our
        # stdin but not from /dev/tty (the controlling terminal). Under sudo that
        # tty is the listener's own pty, so any command that opens /dev/tty can
        # hang on it and corrupt it for the whole listener. Concrete case: an empty
        # $PW turns `mysql -p"$PW"` into a bare `mysql -p`, which prompts on
        # /dev/tty, blocks indefinitely, and leaves the pty in -echo/-isig,
        # silently killing Ctrl-C. With no controlling terminal /dev/tty cannot be
        # opened at all.
        p = subprocess.Popen(["bash", "-c", cmd], stdin=subprocess.DEVNULL,
                             stdout=subprocess.PIPE, stderr=subprocess.PIPE, bufsize=0,
                             env=_child_env(), cwd="/", start_new_session=True)
        streams = {p.stdout.fileno(): (1, p.stdout), p.stderr.fileno(): (2, p.stderr)}
        nbytes = {1: 0, 2: 0}
        teed, last_nl = False, True
        while streams:
            ready, _, _ = select.select(list(streams), [], [])
            for fd in ready:
                tag, f = streams[fd]
                chunk = os.read(fd, 65536)
                if chunk:
                    nbytes[tag] += len(chunk)
                    send_frame(conn, tag, chunk)          # stream to the client
                    if not QUIET:                         # and echo verbatim to the server log
                        # lock is held only across the (non-blocking, file/tty) stderr
                        # write; the blocking network send above is outside it
                        with _io_lock:
                            sys.stderr.buffer.write(chunk)
                            sys.stderr.buffer.flush()
                        teed, last_nl = True, chunk.endswith(b"\n")
                else:
                    f.close()
                    del streams[fd]
        rc = p.wait()
        send_frame(conn, 3, struct.pack(">i", rc))
        if teed and not last_nl:  # keep the DONE line on its own line after un-terminated output
            with _io_lock:
                sys.stderr.buffer.write(b"\n")
                sys.stderr.buffer.flush()
        log("%s DONE: exit=%d in %.2fs (out=%dB err=%dB)" % (peer, rc, time.time() - t0, nbytes[1], nbytes[2]))
    except Exception as e:
        # Keep the detail server-side; tell the client only that it failed.
        log("%s handler error: %s" % (peer, e))
        try:
            send_frame(conn, 4, b"internal-error")
        except OSError:
            pass
    finally:
        try:
            conn.shutdown(socket.SHUT_RDWR)
        except OSError:
            pass
        conn.close()


def _serve_conn(conn, addr, guard):
    try:
        handle(conn, addr, guard)
    finally:
        _conn_sem.release()


def serve():
    ensure_psk()
    # Clean shutdown on Ctrl-C and `kill`. SIGINT is installed explicitly (not left to
    # Python's default) so it fires even when launched in the background, where the shell
    # hands the process SIGINT as ignored and Python would otherwise keep ignoring it.
    signal.signal(signal.SIGINT, signal.default_int_handler)  # -> KeyboardInterrupt
    signal.signal(signal.SIGTERM, lambda *_: sys.exit(0))     # -> SystemExit
    guard = ReplayGuard()
    srv = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    srv.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    try:
        srv.bind((HOST, PORT))
    except OSError as e:
        log("cannot bind %s:%d: %s" % (HOST, PORT, e))
        sys.exit(1)
    srv.listen(16)
    log("listening on %s:%d (uid=%d); one audit line per request follows" % (HOST, PORT, os.geteuid()))
    try:
        while True:
            try:
                conn, addr = srv.accept()
            except (InterruptedError, OSError):
                continue
            if not _conn_sem.acquire(blocking=False):  # at the connection cap: shed load
                log("%s:%d refused: %d concurrent connections" % (addr[0], addr[1], MAX_CONNECTIONS))
                try:
                    conn.close()
                except OSError:
                    pass
                continue
            threading.Thread(target=_serve_conn, args=(conn, addr, guard), daemon=True).start()
    except (KeyboardInterrupt, SystemExit):
        log("shutting down")
    finally:
        try:
            srv.close()
        except OSError:
            pass


# ---------------------------------------------------------------- client side
def sign(psk, cmd):
    ts = str(time.time_ns()).encode()
    nonce = os.urandom(12).hex().encode()
    b64 = base64.b64encode(cmd.encode("utf-8", "surrogateescape"))
    mac = hmac.new(psk, b"%s.%s.%s" % (ts, nonce, b64), hashlib.sha256).hexdigest().encode()
    return b" ".join([ts, nonce, mac, b64]) + b"\n"


def _demux(sock):
    # Returns (exit_code, reject_reason). exit_code stays None until the server sends an
    # explicit exit frame, so a truncated or aborted reply is reported as a failure rather
    # than a false exit 0. Server frame lengths are bounds-checked (the server is trusted,
    # but a bug or impersonator must not make the client allocate gigabytes or crash).
    rc, reason = None, None
    f = sock.makefile("rb")
    while True:
        hdr = f.read(5)
        if not hdr or len(hdr) < 5:
            break
        tag = hdr[0]
        (length,) = struct.unpack(">I", hdr[1:5])
        if length > MAX_FRAME:
            sys.stderr.write("sudo_listener: server sent oversized frame (%d bytes); aborting\n" % length)
            break
        payload = f.read(length) if length else b""
        if len(payload) < length:  # truncated / connection closed mid-frame
            break
        if tag == 1:
            sys.stdout.buffer.write(payload); sys.stdout.buffer.flush()
        elif tag == 2:
            sys.stderr.buffer.write(payload); sys.stderr.buffer.flush()
        elif tag == 3:
            if len(payload) == 4:
                (rc,) = struct.unpack(">i", payload)
            break
        elif tag == 4:
            reason = payload.decode("utf-8", "replace"); break
    return rc, reason


def client(cmd):
    try:
        psk = load_psk()
    except OSError as e:
        sys.stderr.write("sudo_listener(client): cannot read PSK %s: %s\n" % (PSK_PATH, e))
        return 2
    # A rejection arrives before any command output, so retrying is side-effect-free.
    for attempt in range(RETRIES):
        try:
            s = socket.create_connection((HOST, PORT))
        except OSError as e:
            sys.stderr.write("sudo_listener(client): cannot connect to %s:%d: %s\n" % (HOST, PORT, e))
            return 2
        try:
            s.sendall(sign(psk, cmd))
            rc, reason = _demux(s)
        finally:
            s.close()
        if reason is None:
            if rc is None:  # reply ended without an exit frame (truncated/aborted)
                sys.stderr.write("sudo_listener: incomplete reply from server (no exit status)\n")
                return 125
            return rc
        if reason.startswith("stale") and attempt < RETRIES - 1:
            time.sleep(0.01 * (attempt + 1))  # brief backoff, then re-sign with a fresh ts
            continue
        sys.stderr.write("sudo_listener: request rejected by server (%s)\n" % reason)
        return 126
    return 126


USAGE = (
    "usage:\n"
    "  sudo_listener.py [serve] [--host H] [--port N] [--psk PATH] [--quiet]\n"
    "        run the root listener (default action if no subcommand given). each request\n"
    "        is logged and the command's full output is echoed to the server log too,\n"
    "        unless --quiet (or env ROOTRUN_QUIET) is set\n"
    "  sudo_listener.py run [--host H] [--port N] [--psk PATH] '<command>'\n"
    "        send <command> to the listener and stream back its output/exit code\n"
    "\n"
    "defaults:  host=%s  port=%d  psk=%s\n"
    "           override with --host/--port/--psk or env ROOTRUN_HOST/ROOTRUN_PORT/ROOTRUN_PSK\n"
    "  Keep the PSK in a directory only you or root can write; it is a root credential.\n"
)


def _take_opts(args):
    # Pull --host/--port/--psk out of args (overriding env/defaults), return the rest
    # (for `run`, the remainder is the command).
    global HOST, PORT, PSK_PATH, QUIET
    rest, i = [], 0
    while i < len(args):
        a = args[i]
        nxt = args[i + 1] if i + 1 < len(args) else None
        if a == "--host" and nxt is not None:
            HOST = nxt; i += 2
        elif a == "--port" and nxt is not None:
            PORT = int(nxt); i += 2
        elif a == "--psk" and nxt is not None:
            PSK_PATH = nxt; i += 2
        elif a == "--quiet":
            QUIET = True; i += 1
        else:
            rest.append(a); i += 1
    return rest


def main():
    a = sys.argv[1:]
    if a and a[0] in ("-h", "--help"):
        sys.stdout.write(USAGE % (HOST, PORT, PSK_PATH))
        return
    mode = "serve"
    if a and a[0] == "run":
        mode, a = "run", a[1:]
    elif a and a[0] == "serve":
        a = a[1:]
    rest = _take_opts(a)
    if mode == "serve":
        if rest:
            sys.stderr.write("unexpected argument(s): %s\n\n%s" % (" ".join(rest), USAGE % (HOST, PORT, PSK_PATH)))
            sys.exit(64)
        serve()
        return
    if not rest:
        sys.stderr.write(USAGE % (HOST, PORT, PSK_PATH))
        sys.exit(64)
    sys.exit(client(" ".join(rest)))


main()
