#!/usr/bin/env python3
"""Render local HTML to PDF with Playwright/Chromium, then raster every page.

Deterministic iteration for print-style HTML/CSS layouts generated by Claude or
similar tools. This intentionally avoids WeasyPrint, wkhtmltopdf, file://
navigation, HTTP servers, and remote font fetching.
"""
from __future__ import annotations

import argparse
import asyncio
import math
import os
import re
import subprocess
import sys
import time
from pathlib import Path


def _file_uri_for_dir(path: Path) -> str:
    resolved = path.resolve()
    return resolved.as_uri().rstrip("/") + "/"


def _inject_base(html: str, base_href: str) -> str:
    """Add a <base> tag so set_content can resolve relative local assets."""
    base = f'<base href="{base_href}">'
    if re.search(r"<base\s", html, flags=re.I):
        return html
    m = re.search(r"<head[^>]*>", html, flags=re.I)
    if m:
        return html[: m.end()] + "\n" + base + html[m.end() :]
    return base + "\n" + html


class Timing:
    def __init__(self, path: Path | None = None, origin_ms: int | None = None):
        self.t0 = time.perf_counter()
        self.origin_ms = origin_ms
        self.path = path
        if self.path:
            self.path.parent.mkdir(parents=True, exist_ok=True)
            # Do not truncate here. Wrappers own log initialization; this script appends
            # so wrapper-level stages survive in the same timings log.
            if not self.path.exists():
                self.path.write_text("", encoding="utf-8")

    def log(self, event: str, name: str) -> None:
        if self.origin_ms is not None:
            elapsed = (int(time.time() * 1000) - self.origin_ms) / 1000.0
        else:
            elapsed = time.perf_counter() - self.t0
        line = f"[{elapsed:07.2f}s] {event}: {name}"
        print(line, flush=True)
        if self.path:
            with self.path.open("a", encoding="utf-8") as f:
                f.write(line + "\n")


async def render_pdf(html_path: Path, pdf_path: Path, timeout_ms: int, timing: Timing) -> None:
    try:
        from playwright.async_api import async_playwright
    except Exception as exc:  # pragma: no cover
        raise SystemExit(
            "playwright is not available in this environment. use the established "
            "playwright/chromium runtime for this skill rather than switching engines."
        ) from exc

    html = html_path.read_text(encoding="utf-8")
    html = _inject_base(html, _file_uri_for_dir(html_path.parent))

    timing.log("start", "chromium_pdf")
    async with async_playwright() as p:
        candidates = [
            os.environ.get("CHROME_PATH"),
            os.environ.get("CHROMIUM_PATH"),
            "/usr/bin/chromium",
            "/usr/bin/chromium-browser",
            "/usr/bin/google-chrome",
        ]
        executable_path = next((c for c in candidates if c and Path(c).exists()), None)
        launch_kwargs = {"args": ["--no-sandbox", "--disable-dev-shm-usage"]}
        if executable_path:
            launch_kwargs["executable_path"] = executable_path
        timing.log("info", f"chromium_executable={executable_path or 'playwright-managed'}")
        browser = await p.chromium.launch(**launch_kwargs)
        page = await browser.new_page(viewport={"width": 1240, "height": 1754})
        await page.emulate_media(media="print")
        timing.log("info", "media=print")
        await page.set_content(html, wait_until="networkidle", timeout=timeout_ms)
        try:
            await page.evaluate("document.fonts && document.fonts.ready")
        except Exception:
            pass

        font_report = await page.evaluate(
            """() => {
                const meta = document.querySelector('meta[name=\"polisher-required-fonts\"]');
                const required = meta && meta.content ? meta.content.split('|').filter(Boolean) : [];
                const faces = Array.from(document.fonts || []).map(f => ({
                    family: f.family,
                    style: f.style,
                    weight: f.weight,
                    status: f.status
                }));
                const checks = required.map(family => ({
                    family,
                    ok: document.fonts ? document.fonts.check(`16px "${family}"`) : false
                }));
                return {required, checks, errors: faces.filter(f => f.status === 'error'), count: faces.length};
            }"""
        )
        if font_report.get("required"):
            timing.log("info", "required_fonts=" + ",".join(font_report["required"]))
        bad_checks = [c for c in font_report.get("checks", []) if not c.get("ok")]
        bad_faces = font_report.get("errors", [])
        if bad_checks or bad_faces:
            timing.log("fail", "font_verification")
            raise RuntimeError(f"font verification failed: checks={bad_checks}; errored_faces={bad_faces[:5]}")

        await page.pdf(
            path=str(pdf_path),
            print_background=True,
            prefer_css_page_size=True,
            margin={"top": "0mm", "right": "0mm", "bottom": "0mm", "left": "0mm"},
        )
        await browser.close()
    timing.log("ok", "chromium_pdf")


def raster_with_pymupdf(pdf_path: Path, out_dir: Path, dpi: int) -> int:
    import fitz  # type: ignore

    doc = fitz.open(str(pdf_path))
    zoom = dpi / 72.0
    matrix = fitz.Matrix(zoom, zoom)
    for i, page in enumerate(doc, start=1):
        pix = page.get_pixmap(matrix=matrix, alpha=False)
        pix.save(str(out_dir / f"page-{i:02d}.png"))
    return len(doc)


def raster_with_pdftoppm(pdf_path: Path, out_dir: Path, dpi: int) -> int:
    prefix = out_dir / "page"
    subprocess.run(
        ["pdftoppm", "-png", "-r", str(dpi), str(pdf_path), str(prefix)],
        check=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )
    files = sorted(out_dir.glob("page-*.png"))
    for idx, path in enumerate(files, start=1):
        target = out_dir / f"page-{idx:02d}.png"
        if path != target:
            path.rename(target)
    return len(files)


def make_contact_sheet(render_dir: Path, contact_path: Path, thumb_width: int = 420) -> None:
    from PIL import Image, ImageDraw

    pages = sorted(render_dir.glob("page-*.png"))
    if not pages:
        return
    thumbs = []
    for page_path in pages:
        im = Image.open(page_path).convert("RGB")
        scale = thumb_width / im.width
        size = (thumb_width, int(im.height * scale))
        im = im.resize(size)
        thumbs.append((page_path.name, im))

    cols = 3 if len(thumbs) > 4 else 2
    gap = 24
    label_h = 28
    cell_w = thumb_width
    cell_h = max(im.height for _, im in thumbs) + label_h
    rows = math.ceil(len(thumbs) / cols)
    sheet = Image.new("RGB", (cols * cell_w + (cols + 1) * gap, rows * cell_h + (rows + 1) * gap), "white")
    draw = ImageDraw.Draw(sheet)
    for idx, (name, im) in enumerate(thumbs):
        row, col = divmod(idx, cols)
        x = gap + col * (cell_w + gap)
        y = gap + row * (cell_h + gap)
        draw.text((x, y), name, fill=(0, 0, 0))
        sheet.paste(im, (x, y + label_h))
    sheet.save(contact_path, quality=92)


def main() -> int:
    parser = argparse.ArgumentParser(description="Render HTML to PDF with Playwright and raster every page.")
    parser.add_argument("html", type=Path, help="input HTML file")
    parser.add_argument("pdf", type=Path, help="output PDF file")
    parser.add_argument("--render-dir", type=Path, default=None, help="directory for page PNGs")
    parser.add_argument("--contact", type=Path, default=None, help="optional contact sheet image path")
    parser.add_argument("--dpi", type=int, default=150, help="raster DPI for review images")
    parser.add_argument("--timeout-ms", type=int, default=30000, help="Playwright content timeout")
    parser.add_argument("--timing-log", type=Path, default=None, help="append detailed stage timings here")
    parser.add_argument("--timing-origin-ms", type=int, default=None, help="epoch-millisecond origin for shared timing logs")
    args = parser.parse_args()

    timing = Timing(args.timing_log, args.timing_origin_ms)
    timing.log("start", "render_playwright")

    html_path = args.html.resolve()
    pdf_path = args.pdf.resolve()
    if not html_path.exists():
        raise SystemExit(f"input HTML not found: {html_path}")
    pdf_path.parent.mkdir(parents=True, exist_ok=True)

    render_dir = args.render_dir or pdf_path.with_suffix("").parent / (pdf_path.stem + "_renders")
    render_dir.mkdir(parents=True, exist_ok=True)
    for old in render_dir.glob("page-*.png"):
        old.unlink()

    try:
        asyncio.run(render_pdf(html_path, pdf_path, args.timeout_ms, timing))
    except Exception:
        timing.log("fail", "chromium_pdf")
        raise

    timing.log("start", f"raster_pdf dpi={args.dpi}")
    try:
        page_count = raster_with_pymupdf(pdf_path, render_dir, args.dpi)
        timing.log("ok", f"raster_pdf pages={page_count} engine=pymupdf")
    except Exception:
        timing.log("info", "pymupdf raster failed; trying pdftoppm")
        page_count = raster_with_pdftoppm(pdf_path, render_dir, args.dpi)
        timing.log("ok", f"raster_pdf pages={page_count} engine=pdftoppm")

    if args.contact:
        timing.log("start", "contact_sheet internal")
        try:
            make_contact_sheet(render_dir, args.contact)
            timing.log("ok", "contact_sheet internal")
        except Exception as exc:
            timing.log("fail", f"contact_sheet internal: {exc}")
            print(f"warning: could not create contact sheet: {exc}", file=sys.stderr)

    timing.log("ok", "render_playwright")
    print(f"rendered {pdf_path}")
    print(f"rastered {page_count} pages to {render_dir}")
    if args.contact:
        print(f"contact sheet {args.contact}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
